swagger: "2.0"
info:
  title: Toddle
  description: Toddle Backend Task .
  version: 1.0
servers:
  - url: https://journal-backend-t8gt.onrender.com/api/v1
    description: Render Hosted Server
  - url: http://localhost:5000/api/v1
    description: localhost environment
schemes:
  - https
  - http
securityDefinitions:
  JWT:
    type: apiKey
    description: JWT token for authentication. Provide the token with the 'Bearer' prefix. Example "Bearer jwt_token"
    name: Authorization
    in: header
basePath: /api/v1
definitions:
  User:
    type: object
    properties:
      _id:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      role:
        type: string
        enum: ["STUDENT", "TEACHER"]
  Journal:
    type: object
    properties:
      journal_id:
        type: string
      name:
        type: string
      teacher_id:
        type: integer
      description:
        type: string
      created_at:
        type: string
        format: date-time
      file:
        type: string
      published_at:
        type: string
        format: date-time
paths:
  /user/register:
    post:
      tags:
        - User
      summary: Register User
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: User registration details
          required: true
          schema:
            type: object
            properties:
              firstname:
                type: string
              lastname:
                type: string
              email:
                type: string
              password:
                type: string
              role:
                type: string
                enum: ["STUDENT", "TEACHER"]
            required:
              - firstname
              - lastname
              - email
              - password
              - role
      responses:
        "201":
          description: User Registered Successfully
        "400":
          description: Validation Error
        "422":
          description: Email already exists
        "500":
          description: Internal Server Error
  /user/login:
    post:
      tags:
        - User
      summary: Login User
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: User Logged In
        "400":
          description: Validation Error
        "500":
          description: Internal Server Error
  /user/feed:
    get:
      tags: [Feed]
      summary: returns user feed of logged in user (teacher or student)
      security:
        - JWT: []
      responses:
        "200":
          description: returns user feed based on id
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /journal:
    post:
      tags:
        - Journal
      summary: Create a Journal
      consumes:
        - multipart/form-data
      security:
        - JWT: []
      parameters:
        - in: formData
          name: description
          type: string
          description: Description of the journal
        - in: formData
          name: publishedAt
          type: string
          format: date-time
          description: Publication date and time
        - in: formData
          name: file
          type: file
          description: Journal attachment
      responses:
        "200":
          description: Journal created successfully
        "500":
          description: Internal Server Error

  /journal/{id}:
    put:
      tags: [Journal]
      summary: Update an existing journal (Teacher)
      security:
        - JWT: []
      consumes:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the journal entry to be updated
          schema:
            type: integer
            format: int64
        - in: body
          name: body
          description: Update fields for the journal entry
          required: true
          schema:
            type: object
            properties:
              description:
                type: string
                description: Description of the journal entry
      responses:
        "200":
          description: Journal entry updated successfully
        "400":
          description: Bad Request
        "404":
          description: Journal entry not found
        "500":
          description: Internal Server Error

    delete:
      tags:
        - Journal
      summary: Delete a journal entry (Teacher)
      security:
        - JWT: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Journal entry deleted successfully
        "400":
          description: Validation Error
        "404":
          description: Journal entry not found
        "500":
          description: Internal Server Error
  /journal/publish/{id}:
    post:
      tags: [Journal]
      summary: Publish a journal entry (Teacher)
      security:
        - JWT: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the journal entry to be published
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Journal entry published successfully
        "400":
          description: Validation Error
        "404":
          description: Journal entry not found
        "500":
          description: Internal Server Error
